services:
  website:
    build: .
    container_name: website
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.website.rule=Host(`lalacodes.tech`)"
      - "traefik.http.routers.website.entrypoints=websecure"
      - "traefik.http.routers.website.tls.certresolver=myresolver"
    networks:
      - proxy

networks:
  proxy:
    external: true
